monitored_topics:
  - name: "/odometry"
    type: "nav_msgs/Odometry"
    width: 20
    height: 20
  - name: "/imu_data"
    type: "sensor_msgs/Imu"
    width: 20
    height: 16
  - name: "/battery_status"
    type: "sensor_msgs/BatteryState"
    width: 20
    height: 16
  - name: "/geographic_position"
    type: "geographic_msgs/GeoPoint"
    width: 20
    height: 16
  - name: "/geographic_pose"
    type: "geographic_msgs/GeoPose"
    width: 20
    height: 16
